[package]
name = "alreadypro/roact-flipper"
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "src"]

[dependencies]
Roact = "roblox/roact@^1.4.4"
Flipper = "alreadypro/flipper@^2.0.0"